
package com.raven.component;

import com.raven.shadow.ShadowRenderer;
import com.twelvemonkeys.image.ImageUtil;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import static java.awt.image.BufferedImage.TYPE_INT_ARGB;

/**
 *
 * @author dothinhtpr247gmai.com
 */
public class footer extends javax.swing.JPanel {

    /**
     * Creates new form footerLogin
     */
    public footer() {
        initComponents();
        setOpaque(false);
    
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    @Override
    protected void paintComponent(Graphics grphcs) {
        int shadow = 8;
        BufferedImage image = new BufferedImage(getWidth(), getHeight(), BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = image.createGraphics();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setColor(new Color(255,255,255,100));
        g2d.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
        
//        g2d.fill(new Rectangle2D.Double(0, 0, getWidth(), 25));
        g2d.setComposite(AlphaComposite.SrcIn);
        g2d.drawImage(ImageUtil.blur(image.getSubimage(0, 0, getWidth(), getHeight()), 30f), 0, 0, null);
        g2d.setComposite(AlphaComposite.SrcOver);
        
//        g2d.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 15, 15));
//        g2d.fill(new Rectangle2D.Double(0, 0, getWidth(), 25));
        g2d.dispose();
        grphcs.drawImage(new ShadowRenderer(shadow, 0.7f, new Color(0, 0, 0)).createShadow(image), 0, 0, null);
        grphcs.drawImage(image, 0, 0, null);
        super.paintComponent(grphcs);


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
