/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.raven.main;

public class App {
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
//        new Login().setVisible(true);
            new Main().setVisible(true);
//new Signup().setVisible(true);
    }
}
